/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import "./output.css";
import { lensHubProxyContract, PROFILE_ID } from '../lib/config';
import { getURILink } from '../lib/helpers/getURILink';
import { polyfill } from 'interweave-ssr';

async function getProfileData() {
  const profileResponse = await lensHubProxyContract.getProfile(PROFILE_ID);
  return profileResponse;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Used for interweave rendering
  polyfill();

  const profileResponse = await getProfileData();

  return (
    <html>
      <Head>
        <title>DeFi Spartan&#39;s Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-gray-900 w-full">
        <nav className="px-2 sm:px-4 py-2.5 fixed w-full z-20 top-0 left-0">
          <div className="container flex flex-wrap items-center justify-between mx-auto align-middle">
            <div className="flex">
              <div className="rounded-full w-10 h-10 overflow-hidden mr-5">
                <img className="w-full h-full" alt="avatar" src={getURILink(profileResponse.imageURI)} />
              </div>
              <span className="self-center text-xl font-semibold font-mono whitespace-nowrap text-pastel">{profileResponse.handle}</span>
            </div>
            {/* <div className="flex md:order-2">
              <button type="button" className="text-pastel bg-gray-700 hover:bg-gray-800 focus:ring-1 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 ">Connect Wallet</button>
            </div> */}

          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
